#!/usr/bin/env python

import discord
import yaml
import os
from io import StringIO
from mtg_pack_generator.mtg_pack_generator import MtgPackGenerator

dir_path = os.path.dirname(os.path.realpath(__file__))
with open(os.path.join(dir_path, "config.yaml")) as file:
    config = yaml.load(file, Loader=yaml.FullLoader)

client = discord.Client()
generator = MtgPackGenerator(config["mtgjson_path"])
historic_sets = ["klr", "akr", "xln", "rix", "dom", "m19", "grn", "rna",
                 "war", "m20", "eld", "thb", "iko", "m21", "znr"]
standard_sets = ["eld", "thb", "iko", "m21", "znr"]


@client.event
async def on_ready():
    print(f"{client.user} has connected to Discord!")


@client.event
async def on_message(message):
    if message.author == client.user:
        return

    command = message.content.lower()
    p = p_list = None
    if command == "!random":
        p = generator.get_random_pack()
    elif command == "!historic":
        p = generator.get_random_pack(historic_sets)
    elif command == "!standard":
        p = generator.get_random_pack(standard_sets)
    elif command in [f"!{set}" for set in historic_sets]:
        p = generator.get_pack(command.lstrip("!"))
    elif command == "!chaossealed":
        p_list = generator.get_random_pack(historic_sets, n=6)
    elif command in [f"!{set}sealed" for set in historic_sets]:
        p_list = generator.get_pack(command.lstrip("!").rstrip("sealed"), n=6)
    elif command == "!help":
        await message.channel.send(
            "you can give it one of the following commands atm:\n"
            "`!random`: generates a random pack from the whole history "
            "of Magic\n"
            "`!historic`: generates a random historic pack\n"
            "`!standard`: generates a random standard pack\n"
            "`!{setcode}`: generates a pack from the indicated set, available "
            "on Arena (e.g., `!znr` generates a *Zendikar Rising* pack)\n"
            "`!{setcode}sealed`: generates 6 packs from the indicated set, "
            "available on Arena (e.g., `!znrsealed` generates 6 *Zendikar "
            "Rising* packs)\n"
            "`!chaossealed`: generates 6 random historic packs\n"
            "`!help`: shows this message"
        )

    if p:
        await message.channel.send(f"**{p.name}** "
                                   f"(generated by {message.author.mention})\n"
                                   f"```\n{p.get_arena_format()}\n```")
    elif p_list:
        pool = ""
        sets = ""
        for p in p_list:
            sets = sets + f"{p.set.code}, "
            pool = pool + f"{p.get_arena_format()}\n"
        sets = sets + ""
        file = StringIO(pool)
        await message.channel.send(f"**Sealed starting pool** "
                                   f"(generated by {message.author.mention})\n"
                                   f"Content: [{sets.rstrip(', ')}]",
                                   file=discord.File(
                                       file,
                                       filename=f"{message.author}_pool.txt"))

client.run(config["token"])
