# copy, rename to 'config.yaml', and fill with your data

### API TOKENS ###
# Your Discord bot API token
discord_token: your_discord_bot_token

###### PATHS #####
# Check utils folder for scripts to download what the bot needs to work
# Path to the AllPrintings.sqlite file downloaded from MTGjson
mtgjson_path: /absolute/path/to/AllPrintings.sqlite
# comment to exclude set images
set_img_path: /absolute/path/to/img/sets/

## OTHER CONFIG ##
# Discord messages using this prefix will be read by the bot as commands
command_prefix: "!"
# Logging level can be: DEBUG, INFO, WARNING, ERROR
logging_level: INFO
# Validate MTGjson data before starting the bot
validate_data: TRUE