#### Black ####
[tool.black]
line-length = 79


#### Mypy ####
[[tool.mypy.overrides]]
module = [
  "aiohttp.*",
  "aioresponses.*",
  "discord.*",
  "imageio.*",
  "numpy.*",
  "parse.*",
]
ignore_missing_imports = true


#### PyTest ####
[tool.pytest.ini_options]
testpaths = "tests"
asyncio_mode = "auto"
