# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check with black
      run: |
        black --check .
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Make config file
      run: |
        echo "discord_token: xxx" > config.yaml
        echo "imgur_client_id: yyy" >> config.yaml
        echo "mtgjson_path: data/AllPrintings.json" >> config.yaml
        echo "jmp_decklists_path: data/JMP" >> config.yaml
        echo "set_img_path: boostertutor/img/sets/" >> config.yaml
        echo "command_prefix: !" >> config.yaml
        echo "pack_logging: True" >> config.yaml
    - name: Download data
      run: |
        mkdir data
        mkdir data/JMP
        python utils/mtgjson_downloader.py
    - name: Test with pytest
      run: |
        pytest
