# This workflow will check MD linting of README.md when edited

name: Lint README

on:
  push:
    paths:
      - 'README.md'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Markdown Linting Action
      uses: avto-dev/markdown-lint@v1.5.0
