# This workflow will check MD linting of README.md when edited

name: Lint README

on:
  push:
    paths:
      - 'README.md'

jobs:
  lint:
    name: Lint README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4   
    - name: Lint
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: './README.md'
