# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python checks and tests

on: [push, pull_request]

jobs:
  check:
    name: Code check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy pytest
        pip install types-PyYAML types-requests types-aiofiles
    - name: Check with black
      run: |
        black --check .
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Check types with mypy
      run: |
        mypy .

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Make config file
      run: |
        echo "discord_token: ${{ secrets.DISCORD_TOKEN }}" > config.yaml
        echo "imgur_client_id: ${{ secrets.IMGUR_CLIENT_ID }}" >> config.yaml
        echo "mtgjson_path: data/AllPrintings.json" >> config.yaml
        echo "jmp_decklists_path: data/JMP/" >> config.yaml
        echo "set_img_path: boostertutor/img/sets/" >> config.yaml
        echo "command_prefix: !" >> config.yaml
        echo "pack_logging: True" >> config.yaml
    - name: Download data
      run: |
        mkdir -p data/JMP
        python -m boostertutor.utils.mtgjson_downloader --jmp
    - name: Test with pytest
      run: |
        pytest --cov=boostertutor --cov-report term-missing:skip-covered
